name: 'TestChecker2023'
description: 'Purge content on the Akamai network from your Github workflow'
branding:
  icon: 'cloud-off'
  color: 'gray-dark'
inputs:
  command:
    description: 'Purge command (delete, invalidate)'
    required: true
  type:
    description: 'Purge type (tag, cpcode, url)'
    required: true
    default: 'tag'
  ref:
    description: 'Reference'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: ls
      run: |
            echo $GITHUB_WORKSPACE
            printenv
      shell: bash
      
  
